# Generated by Django 5.0.2 on 2024-02-22 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(25)], verbose_name='Fruit Name')),
                ('image_url', models.URLField(verbose_name='Fruit Image URL')),
                ('description', models.TextField(verbose_name='Fruit Description')),
                ('nutrition', models.TextField(blank=True, null=True, verbose_name='Nutrition Info')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='profiles.profile')),
            ],
        ),
    ]
