# Generated by Django 5.0.2 on 2024-02-23 07:37

import MyPlant_App.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(10)])),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), MyPlant_App.profiles.validators.validate_profile_name])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), MyPlant_App.profiles.validators.validate_profile_name])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
