# Generated by Django 5.0.2 on 2024-02-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_genre'),
        ('profiles', '0002_alter_profile_age_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='profiles.profile'),
        ),
    ]
