# Generated by Django 5.0.2 on 2024-02-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('Outdoor_Plants', 'Outdoor Plants'), ('Indoor_Plants', 'Indoor Plants')], max_length=14),
        ),
    ]
