# Generated by Django 5.0.2 on 2024-02-24 07:40

import World_Of_Speed_App.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 chars long!'), django.core.validators.MaxLengthValidator(15), World_Of_Speed_App.profiles.validators.validate_username])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(21)])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
