# Generated by Django 4.2.4 on 2023-10-24 12:46

from django.db import migrations


def add_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()

    for c_person in all_persons:
        if c_person.age <= 12:
            c_person.age_group = 'Child'
        elif 13 <= c_person.age <= 17:
            c_person.age_group = 'Teen'
        else:
            c_person.age_group = 'Adult'

    person.objects.bulk_update(all_persons, ['age_group'])


def reverse_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()
    age_group_default = person._meta.get_field('age_group').default

    for c_person in all_persons:
        c_person.age_group = age_group_default

    person.objects.bulk_update(all_persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(add_age_group, reverse_code=reverse_age_group)
                  ]
