# Generated by Django 4.2.4 on 2023-10-22 07:29

from django.db import migrations


def add_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    all_persons = person.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.add_age_group = 'Child'
        elif 13 <= person.age <= 17:
            person.add_age_group = 'Teen'
        else:
            person.add_age_group = 'Adult'

        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [migrations.RunPython(add_age_group)
                  ]