# Generated by Django 4.2.4 on 2023-10-22 09:04

from django.db import migrations


def set_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    all_items = item.objects.all()

    for item in all_items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

        item.save()


def reverse_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    all_items = item.objects.all()
    for item in all_items:
        item.rarity = 'empty'


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [migrations.RunPython(set_item_rarity, reverse_code=reverse_item_rarity)
                  ]
