# Generated by Django 4.2.4 on 2023-10-22 09:14

from django.db import migrations


def set_price_based_on_brands_name(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone.objects.all()

    for c_smartphone in all_smartphones:
        c_smartphone.price = len(c_smartphone.brand) * 120

        c_smartphone.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_based_on_brands_name)
    ]
