# Generated by Django 4.2.4 on 2023-10-22 09:19

from django.db import migrations


def set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone.objects.all()

    for c_smartphone in all_smartphones:
        if c_smartphone.price >= 750:
            c_smartphone.category = 'Expensive'
        else:
            c_smartphone.category = 'Cheap'

        c_smartphone.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_auto_20231022_1214'),
    ]

    operations = [
        migrations.RunPython(set_category)
    ]
