# Generated by Django 4.2.4 on 2023-10-24 13:28

from django.db import migrations
from django.utils import timezone


def set_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')
    all_orders = order.objects.all()

    for c_order in all_orders:
        if c_order.status == 'Pending':
            c_order.delivery = c_order.order_date + timezone.timedelta(days=3)
            c_order.save()
        elif c_order.status == 'Completed':
            c_order.warranty = '24 months'
            c_order.save()
        else:
            c_order.delete()


def reverse_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')
    all_orders = order.objects.all()
    order_delivery_default = order._meta.get_field('delivery').default
    order_warranty_default = order._meta.get_field('warranty').default

    for c_order in all_orders:
        c_order.delivery = order_delivery_default
        c_order.warranty = order_warranty_default

    order.objects.bulk_update(all_orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty, reverse_code=reverse_delivery_and_warranty)
    ]
