# Generated by Django 4.2.4 on 2023-10-22 09:47
import datetime

from django.db import migrations


def set_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')
    all_orders = order.objects.all()

    for c_order in all_orders:
        if c_order.status == 'Pending':
            c_order.delivery = c_order.order_date + datetime.timedelta(days=3)
            c_order.save()
        elif c_order.status == 'Completed':
            c_order.warranty = '24 months'
            c_order.save()
        else:
            c_order.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty)
    ]
