# Generated by Django 5.0.1 on 2024-02-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PhotoLike',
        ),
    ]
