# Generated by Django 5.0.1 on 2024-02-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_comment_options_alter_comment_photo_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='photos.petphoto'),
        ),
    ]
