# Generated by Django 5.0.2 on 2024-02-22 22:40

import Fruitipedia_App.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(25), Fruitipedia_App.profiles.validators.validate_name], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(35), Fruitipedia_App.profiles.validators.validate_name], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, unique=True, validators=[django.core.validators.MaxLengthValidator(40)], verbose_name='Email')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)], verbose_name='Password')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='Age')),
            ],
        ),
    ]
